name: Run Unit Tests

# Exécuter à chaque push ou pull request sur la branche main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Configuration du job pour s'exécuter sur Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python et les dépendances
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Vous pouvez spécifier une version ici (ex: '3.12')

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances du projet

      # Étape 3 : Exécuter les tests avec pytest
      - name: Run unit tests
        run: |
          pytest --maxfail=1 --disable-warnings  # Exécuter les tests avec pytest

